chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path('<int:team_id>', views.TeamChat.as_view(), name='team-chat'),
    path('<int:team_id>/wiadomosci', views.LoadMessages.as_view(), name='load-messages'),
    path('<int:team_id>/ustawienia', views.UpdateTeamSettings.as_view(), name='update-team-settings'),
    path('<int:team_id>/druzyna', views.DeleteTeam.as_view(), name='delete-team'),
    path('<int:team_id>/czlonkowie', views.RemoveUserFromTeam.as_view(), name='delete-team-member'),
    path('<int:team_id>/dolacz/<int:team_member_id>', views.JoinChat.as_view(), name='join-chat'),
]

notifications/urls.py
from django.urls import path
from . import views

app_name='notifications'
urlpatterns = [
    #Join announcement
    path('join-announcement', views.JoinAnnouncement.as_view(), name='join-announcement'),
    path('cancel-join-announcement', views.CancelJoinAnnouncement.as_view(), name='cancel-join-announcement'),
    path('join-announcement-acceptance', views.JoinAnnouncementAcceptance.as_view(), name='join-announcement-acceptance'),
    path('join-announcement-rejection', views.JoinAnnouncementRejection.as_view(), name='join-announcement-rejection'),
    # Join Team
    path('join-team', views.JoinTeam.as_view(), name='join-team'),
    path('cancel-join-team', views.CancelJoinTeam.as_view(), name='cancel-join-team'),
    path('join-team-acceptance', views.JoinTeamAcceptance.as_view(), name='join-team-acceptance'),
    path('join-team-rejection', views.JoinTeamRejection.as_view(), name='join-team-rejection'),
]

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("dla-tworcow/", views.ForCreators.as_view(), name="for-creators"),
    path("dla-organizacji/", views.ForOrganizations.as_view(), name="for-organizations"),
    path("przegladaj-ogloszenia/", views.AnnouncementList.as_view(), name="announcement-list"),
    path("moje-ogloszenie/", views.MyAnnouncement.as_view(), name="my-announcement"),
    path("ogloszenie/<int:id>/", views.AnnouncementDetails.as_view(), name="announcement-detail"),
    path("stworz-ogloszenie/", views.AnnouncementCreate.as_view(), name="announcement-create"),
    path("edytuj-ogłoszenie/", views.AnnouncementUpdate.as_view(), name="announcement-edit"),
    path("usun-ogłoszenie/", views.AnnouncementDelete.as_view(), name="announcement-delete"),
    path("moje-druzyny/", views.MyTeams.as_view(), name="my-teams"),
    path("edytuj-profil/", views.EditProfile.as_view(), name="edit-profile"),
    path("zaloguj/", views.Login.as_view(), name="login"),
    path("zarejestruj/", views.Register.as_view(), name="register"),
    path("zarejestruj/tworca/", views.RegisterCreator.as_view(), name="register-creator"),
    path("zarejestruj/organizacja/", views.RegisterOrganization.as_view(), name="register-organization"),
    path("wyloguj/", views.Logout.as_view(), name="logout"),
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.postgres.fields import ArrayField
from ckeditor.fields import RichTextField
from django.contrib import admin
from django.urls import reverse
from .managers import (
    CustomAccountManager, 
    AnnouncementQuerySetManager, 
    CityManager
)

import bleach


# Set ckeditor sanitizing rules
bleach.sanitizer.ALLOWED_TAGS += ['p', 'span', 'u', 'ul', 'ol', 'hr', 'img' ,'div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6','pre', 'address', 'strong', 'br']
bleach.sanitizer.ALLOWED_ATTRIBUTES.update({'*': ['style'], 'img': ['alt', 'src']})
bleach.sanitizer.ALLOWED_STYLES += ['color', 'font-size', 'text-align', 'list-style-type', 'background-color', 'height', 'width', 'margin-left', 'float', 'margin', 'border-width', 'border-style']

# ===== Choices =====
# info https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types
class Roles(models.TextChoices):
    FRONTEND = ('FE', 'Front-End Developer')
    FULLSTACK = ('FS', 'Full-Stack Developer')
    BACKEND = ('BE', 'Back-End Developer')
    DESIGNER = ('GD', 'Graphic Designer')

    @classmethod
    def get_labels_by_values(cls, values):
        return [role_name for (role_value, role_name) in Roles.choices if role_value in values]


# ===== Models =====
class User(AbstractBaseUser,PermissionsMixin):
    objects = CustomAccountManager()

    email = models.EmailField(unique=True, blank=False)
    is_organization = models.BooleanField('is organization?', default=False)
    is_creator = models.BooleanField('is creator?', default=False)
    is_staff = models.BooleanField('staff status', default=False)
    is_active = models.BooleanField('active', default=True)
    date_joined = models.DateTimeField('date joined', auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class Voivodeship(models.Model):
    name = models.CharField(max_length=255,  unique=True)

    def __str__(self):
        return self.name


class City(models.Model):
    objects = CityManager()

    voivodeship = models.ForeignKey(Voivodeship, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Cities'
        ordering = ('name',)
        unique_together = ['voivodeship', 'name']

    def __str__(self):
        return self.name


class Organization(models.Model):
    ORGANIZATION_CATEGORY_CHOICES = [
        ('DP', 'Działalnośc prospołeczna'),
        ('EiW', 'Edukacja i wychowanie'),
        ('WON', 'Wspanie osób niepełnosprawnych'),
        ('KSiT', 'Kultura, Sztuka i Technologia'),
        ('OZiZ', 'Ochrona zdrowia i życia'),
        ('DCh', 'Działalność charytatywna'),
        ('PDzi', 'Pomoc Dzieciom'),
        ('SiR', 'Sport i rekreacja'),
        ('OSiPZ', 'Ochorna środowiska i praw zwierząt')
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField('organization\'s name', max_length=255, unique=True)
    category = models.CharField(max_length=10, choices=ORGANIZATION_CATEGORY_CHOICES)
    phone_number = models.CharField('phone number', max_length=9, blank=True, null=True)
    fb_url = models.URLField('facebook page URL', blank=True, null=True)
    twitter_url = models.URLField('twitter accout URL', blank=True, null=True)
    KRS = models.CharField(max_length=10, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Creator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField('first name', max_length=150, blank=True, null=True)
    last_name = models.CharField('last name', max_length=150, blank=True, null=True)


    def __str__(self):
        return f'{self.user}' + \
               (f' ({self.last_name}, {self.first_name})' if (self.first_name and self.last_name) else '')


class Announcement(models.Model):
    objects = AnnouncementQuerySetManager.as_manager()

    organization = models.OneToOneField(Organization, on_delete=models.CASCADE)
    logo = models.ImageField('organization\'s logo', upload_to='logos/', blank=True, null=True)
    content = RichTextField('what needs to be done', blank=False, null=False)
    #TODO images of the future website??
    old_website = models.URLField('previous organization\'s website', blank=True, null=True)
    created_on = models.DateTimeField('created on', auto_now_add=True)

    def __str__(self):
        return f'Announcement by {self.organization}'

    def get_absolute_url(self):
        return reverse('webapp:announcement-detail', kwargs={'id': self.id})

    def is_author(self, user):
        return self.organization.user == user

    def save(self, *args, **kwargs):
        self.content = bleach.clean(self.content)
        super().save(*args, **kwargs)


class Team(models.Model):

    TECHNOLOGIES_CHOICES = [
        ('PY', 'python'),
        ('NJS', 'node.js'),
        ('PHP', 'php'),
        ('ROR', 'ruby on rails'),
        ('JSP', 'java'),
        ('ASX', '.net'),
        ('GO', 'golang'),
        ('HC', 'html&css'),
        ('JS', 'javascript'),
        ('TS', 'typescript'),
        ('JSX', 'react'),
        ('ANG', 'angular'),
        ('VUE', 'vue.js'),
        ('CPP', 'c++'),
        ('C', 'c'),
        ('RN', 'react native'),
        ('FL', 'flutter'),
        ('SC', 'scala'),
        ('EX', 'elixir'),
        ('KT', 'kotlin')
    ]


    announcement = models.OneToOneField(Announcement, on_delete=models.CASCADE)
    is_closed = models.BooleanField('is closed?', default=False)
    members = models.ManyToManyField(Creator, related_name='teams', through='TeamMember')
    # info https://docs.djangoproject.com/en/dev/ref/contrib/postgres/fields/#arrayfield
    our_stack = ArrayField(
        models.CharField('What technologies we use?', max_length=3, choices=TECHNOLOGIES_CHOICES),
        blank=True, 
        null=True
    )
    looking_for = ArrayField(
        models.CharField('looking for those roles', max_length=2, choices=Roles.choices),
        blank=True, 
        null=True
    )

    def __str__(self):
        return f'Team for {self.announcement}'

    def get_absolute_url(self):
        return reverse("chat:team-chat", kwargs={"team_id": self.id})

    def get_admin(self):
        return self.teammember_set.get(is_admin=True).creator.user


# Jak używać many to many https://youtu.be/-HuTlmEVOgU?t=890
class TeamMember(models.Model):
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    role = models.CharField(max_length=2, choices=Roles.choices, null=True)
    is_admin = models.BooleanField('is admin?', default=False)
    nick = models.CharField(max_length=50, null=True)
    joined = models.BooleanField('user joined?', default=False)

    @admin.display(description='Creator')
    def show_creator(self):
        return str(self.creator)    

    @admin.display(description='Team')
    def show_team(self):
        return str(self.team)

    class Meta:
        unique_together = ['creator', 'team']

webapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from ckeditor.widgets import CKEditorWidget
from django.forms import widgets
from .models import Announcement, Team, User, Organization, Creator, City, Roles
from django.db import transaction

class OrganizationFieldsMixin(forms.ModelForm):
    name = forms.CharField(required=True, label='Nazwa organizacji',
                           widget=forms.TextInput(attrs={'aria-label': 'Podaj nazwę organizacji'}))
    category = forms.ChoiceField(choices=Organization.ORGANIZATION_CATEGORY_CHOICES, label='Kategoria', 
                                 widget=forms.Select(attrs={'aria-label': 'Wybierz kategorię'}))
    phone_number = forms.CharField(required=False, label='Numer telefonu', max_length=9,
                                   widget=forms.TextInput(attrs={'aria-label': 'Wpisz numer telefonu'}))
    fb_url = forms.URLField(required=False, label='Strona na Facebook', 
                            widget=forms.URLInput(attrs={
                                'placeholder': 'Wpisz adres strony (np. https://www.facebook.com/PolskaAkcjaHumanitarna/)',
                                'aria-label': 'Wpisz adres strony (np. https://www.facebook.com/PolskaAkcjaHumanitarna/)'
                            }))
    twitter_url = forms.URLField(required=False, label='Konto na Twitter', 
                                 widget=forms.URLInput(attrs={
                                     'placeholder': 'Wpisz adres strony (np. https://twitter.com/PAH_org)',
                                     'aria-label': 'Wpisz adres strony (np. https://twitter.com/PAH_org)'
                                 }))
    KRS = forms.CharField(required=False, label='Numer KRS', max_length=10,
                          widget=forms.TextInput(attrs={'aria-label': 'Podaj numer KRS'}))                   
    city = forms.ModelChoiceField(required=False, label='Miasto', queryset=City.objects.all())


class OrganizationRegisterForm(UserCreationForm, OrganizationFieldsMixin):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get('email')
        user.is_organization = True
        user.save()
        organization = Organization(user=user)
        organization.name = self.cleaned_data.get('name')
        organization.category = self.cleaned_data.get('category')
        organization.phone_number = self.cleaned_data.get('phone_number')
        organization.fb_url = self.cleaned_data.get('fb_url')
        organization.twitter_url = self.cleaned_data.get('twitter_url')
        organization.KRS = self.cleaned_data.get('KRS')
        organization.city = self.cleaned_data.get('city')
        organization.save()
        return user
        
    def clean(self):
        cleaned_data = super().clean()

        fb_url = cleaned_data.get('fb_url')
        twitter_url = cleaned_data.get('twitter_url')

        if fb_url:
            if 'facebook.com' not in fb_url:
                self.add_error('fb_url', 'Podany adres nie należy do Facebook\'a') 
        
        if twitter_url:
            if 'twitter.com' not in twitter_url:
                self.add_error('twitter_url', 'Podany adres nie należy do Twitter\'a') 

        return cleaned_data


class CreatorRegisterForm(UserCreationForm):
    first_name = forms.CharField(required=False, label='Imię',
                                 widget=forms.TextInput(attrs={'aria-label': 'Podaj imię'}))
    last_name = forms.CharField(required=False, label='Nazwisko',
                                widget=forms.TextInput(attrs={'aria-label': 'Podaj nazwisko'}))

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get('email')
        user.is_creator = True
        user.save()
        creator = Creator(user=user)
        creator.first_name = self.cleaned_data.get('first_name')
        creator.last_name = self.cleaned_data.get('last_name')
        creator.save()
        return user


class AnnouncementForm(forms.ModelForm):
    logo = forms.ImageField(required=False, label='Logo organizacji',
                            widget=forms.FileInput(attrs={'aria-label': 'Prześlij logo organizacji'}))
    old_website = forms.URLField(required=False, label='Adres obecnej strony (jeśli istnieje)',
                                 widget=forms.URLInput(attrs={'aria-label': 'Adres obecnej strony (jeśli istnieje)'}))
    content  = forms.CharField(required=True, label='Treść ogłoszenia', 
                               widget=CKEditorWidget(attrs={'aria-label': 'Podaj treść ogłoszenia'}))
    #TODO def clean_content(self): - NO SCRIPTS

    class Meta:
        model = Announcement
        fields = ['content', 'logo', 'old_website']


class OrganizationEditForm(OrganizationFieldsMixin):
    class Meta:
        model = Organization
        fields = ['name', 'category', 'phone_number', 'fb_url', 'twitter_url', 'KRS', 'city']


class CreatorEditForm(forms.ModelForm):
    class Meta:
        model = Creator
        fields = ['first_name', 'last_name']


class TeamJoinForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['looking_for']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        team = kwargs['instance']
        # Show only roles that are looked for by the team
        limited_choices = [(role_value, role_name) for (role_value, role_name) in Roles.choices if role_value in team.looking_for]
        self.fields['looking_for'] = forms.ChoiceField(label='Wybierz rolę', choices=limited_choices)

webapp/templates/webapp/partials/annnouncement_preview.html
{% comment %} #TODO use better data on preview {% endcomment %}
<div class="card mb-3 bg-light border-info">
    <div class="card-body">
        <h5 class="card-title">{{ announcement.organization.name }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ announcement.created_on }}</h6>
        <div>            
            {% include 'webapp/partials/show_announcement_badge.html' with announcement_state=announcement.extra_data.announcement_state team=announcement.extra_data.team %}
        </div>
        <div class="card-footer">
            {{ announcement.organization.get_category_display }}
        </div>
        <a href="{% url 'webapp:announcement-detail' id=announcement.id %}" class="btn btn-primary stretched-link">Poznaj szczegóły</a>
    </div>
</div>

webapp/templates/webapp/partials/announcement_delete_modal.html
<!-- Delete Team Modal -->
<div class="modal fade" id="deleteAnnouncementModal" tabindex="-1" aria-labelledby="deleteAnnouncementModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteAnnouncementModalLabel">Jesteś pewien?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Ta akcja jest nieodwracalna i będzie skutkowała usunięciem ogłoszenia jak i powiązanej z nią drużyny!
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Anuluj</button>
            <form action="{% url 'webapp:announcement-delete' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Usuń</button>
            </form>
        </div>
        </div>
    </div>
</div>

webapp/templates/webapp/partials/detail_no_team.html
{% load notifications_tags %}


{% join_request_send join_request_type='Announcement' as join_announcement_request_send %}

{% if not join_announcement_request_send %}
    <form action="{% url "notifications:join-announcement" %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="organization" value="{{ organization_id }}">
        <input type="submit" class="btn btn-secondary" value="Zgłoś się do ogłoszenia">
    </div>
{% else %}
    <form action="{% url "notifications:cancel-join-announcement" %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="organization" value="{{ organization_id }}">
        <input type="submit" class="btn btn-secondary" value="Wycofaj zgłoszenie do ogłoszenia">
    </div>
{% endif %}

webapp/templates/webapp/partials/detail_team_opened.html
{% load crispy_forms_tags %}
{% load notifications_tags %}
{% load custom_tags %}


{% join_request_send join_request_type='Team' as join_team_request_send %}
{% get_arrayfield_display team arrayfield='our_stack' as our_stack%}
{% get_arrayfield_display team arrayfield='looking_for' as looking_for%}

<div>Our stack: {{ our_stack }}</div>
<div>Looking for: {{ looking_for }}</div>
{% comment %} #TODO show badge team opened + stack + looking for {% endcomment %}
    {% if not join_team_request_send %}
    <form action="{% url "notifications:join-team" %}" method="POST">
        {% csrf_token %}
        {{looking_for_form|crispy}}
        <input type="hidden" name="organization" value="{{ organization_id }}">
        <input type="hidden" name="team_id" value="{{ team.id }}">
        <input type="submit" class="btn btn-secondary" value="Zgłoś się do drużyny">
    </div>
    <div>Team opened - request not send</div>
{% else %}
    <form action="{% url "notifications:cancel-join-team" %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="team_id" value="{{ team.id }}">
        <input type="submit" class="btn btn-secondary" value="Wycofaj zgłoszenie do drużyny">
    </div>
    <div>Team opened - request send</div>
{% endif %}

webapp/templates/webapp/partials/form_no_team.html
{% load notifications_tags %}


{% join_request_send join_request_type='Announcement' as join_announcement_request_send %}

{% if not join_announcement_request_send %}
    <form action="{% url "notifications:join-announcement" %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="organization" value="{{ organization_id }}">
        <input type="submit" class="btn btn-secondary" value="Zgłoś się do ogłoszenia">
    </div>
{% else %}
    <form action="{% url "notifications:cancel-join-announcement" %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="organization" value="{{ organization_id }}">
        <input type="submit" class="btn btn-secondary" value="Wycofaj zgłoszenie do ogłoszenia">
    </div>
{% endif %}

webapp/templates/webapp/partials/form_team_opened.html
{% load crispy_forms_tags %}
{% load notifications_tags %}


{% join_request_send join_request_type='Team' as join_team_request_send %}

{% if not join_team_request_send %}
    <form action="{% url "notifications:join-team" %}" method="POST">
        {% csrf_token %}
        {{looking_for_form|crispy}}
        <input type="hidden" name="organization" value="{{ organization_id }}">
        <input type="hidden" name="team_id" value="{{ team.id }}">
        <input type="submit" class="btn btn-secondary" value="Zgłoś się do drużyny">
    </div>
    <div>Team opened - request not send</div>
{% else %}
    <form action="{% url "notifications:cancel-join-team" %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="team_id" value="{{ team.id }}">
        <input type="submit" class="btn btn-secondary" value="Wycofaj zgłoszenie do drużyny">
    </div>
    <div>Team opened - request send</div>
{% endif %}

webapp/templates/webapp/partials/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index'%}">Dobrodzieje</a>
      <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> -->
  
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'index' %}active{% endif %}" href="{% url 'index'%}">O stronie</a>
          </li>          
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'announcement-list' %}active{% endif %}" href="{% url 'announcement-list'%}">Przeglądaj ogłoszenia</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'for-organizations' %}active{% endif %}" href="{% url 'for-organizations'%}">Dla organizacji</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'for-creators' %}active{% endif %}" href="{% url 'for-creators'%}">Dla twórców</a>
          </li>

        </ul>
        <ul class="navbar-nav me-end">
          {% if user.is_organization %}
            <li class="nav-item">
              <a class="nav-link {% if navbar_active == 'my-announcement' %}active{% endif %}" href="{% url 'my-announcement'%}">Moje ogłoszenia</a>
            </li>
          {% endif %}          
          {% if user.is_creator %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'my-teams'%}">Moje Drużyny</a>
            </li>
          {% endif %}
          {% if user.is_authenticated %}          
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
                </svg>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
              <div class="dropdown-menu dropdown-menu-end">
                <a class="dropdown-item" href="{% url 'edit-profile'%}">Ustawienia Konta</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Wyloguj się</a>
              </div>
            </li>
          {% endif %}
          {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if navbar_active == 'login' %}active{% endif %}" href="{% url 'login' %}">Zaloguj się</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if navbar_active == 'register' %}active{% endif %}" href="{% url 'register' %}">Zarejestruj się</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

webapp/templates/webapp/partials/show_announcement_badge.html
{% load custom_tags %}

{% comment %} #TODO show better badge {% endcomment %}

{% if announcement_state == 'no team' %}
    no team
{% elif announcement_state == 'team opened' %}
    {% get_arrayfield_display team arrayfield='our_stack' as our_stack%}
    {% get_arrayfield_display team arrayfield='looking_for' as looking_for%}

    <div>Our stack: {{ our_stack }}</div>
    <div>Looking for: {{ looking_for }}</div>
{% elif announcement_state == 'team closed' %}
    team closed
{% elif announcement_state == 'team member' %}
    team member
{% endif %}

webapp/templates/webapp/partials/team_preview.html
{% load custom_tags %}

{% get_arrayfield_display team arrayfield='our_stack' as our_stack%}
{% get_arrayfield_display team arrayfield='looking_for' as looking_for%}

<div class="card mb-3 bg-light border-info">
    <div class="card-body">
        <h5 class="card-title">{{ team.announcement.organization }}</h5>
        <p>Zamknięta? - {{ team.is_closed }}</p>
        <p>
            Stack 
            <ul>
                {% for technology in our_stack %}
                    <li>{{technology}}</li>
                {% empty %}
                    -
                {% endfor %}
            </ul>
        </p>
        <p>
            Poszukiwani 
            <ul>
                {% for creator in looking_for %}
                    <li>{{creator}}</li>
                {% empty %}
                    -
                {% endfor %}
            </ul>
        </p>
        <p class="card-text">
            Drużyna:
            <ul>
                {% for team_member in team.teammember_set.all %}
                    {% if team_member.joined %}
                        <li>{{ team_member.nick }} - {{ team_member.get_role_display }}</li>
                       
                    {% endif %}
                {% endfor %}
            </ul>
        </p>
        <a href="{{ team.get_absolute_url }}" class="btn btn-primary stretched-link">Przejdź do czatu</a>
    </div>
</div>