chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path('<int:team_id>', views.TeamChat.as_view(), name='team-chat'),
    path('<int:team_id>/wiadomosci', views.LoadMessages.as_view(), name='load-messages'),
    path('<int:team_id>/ustawienia', views.UpdateTeamSettings.as_view(), name='update-team-settings'),
    path('<int:team_id>/druzyna', views.DeleteTeam.as_view(), name='delete-team'),
    path('<int:team_id>/czlonkowie', views.RemoveUserFromTeam.as_view(), name='delete-team-member'),
    path('<int:team_id>/dolacz/<int:team_member_id>', views.JoinChat.as_view(), name='join-chat'),
]

dobrodzieje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('chat/', include('chat.urls')),
    path('notifications/', include('notifications.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("dla-tworcow/", views.ForCreators.as_view(), name="for-creators"),
    path("dla-organizacji/", views.ForOrganizations.as_view(), name="for-organizations"),
    path("przegladaj-ogloszenia/", views.AnnouncementList.as_view(), name="announcement-list"),
    path("moje-ogloszenie/", views.MyAnnouncement.as_view(), name="my-announcement"),
    path("ogloszenie/<int:id>/", views.AnnouncementDetails.as_view(), name="announcement-detail"),
    path("stworz-ogloszenie/", views.AnnouncementCreate.as_view(), name="announcement-create"),
    path("edytuj-ogłoszenie/", views.AnnouncementUpdate.as_view(), name="announcement-edit"),
    path("usun-ogłoszenie/", views.AnnouncementDelete.as_view(), name="announcement-delete"),
    path("moje-druzyny/", views.MyTeams.as_view(), name="my-teams"),
    path("edytuj-profil/", views.EditProfile.as_view(), name="edit-profile"),
    path("zaloguj/", views.Login.as_view(), name="login"),
    path("zarejestruj/", views.Register.as_view(), name="register"),
    path("zarejestruj/tworca/", views.RegisterCreator.as_view(), name="register-creator"),
    path("zarejestruj/organizacja/", views.RegisterOrganization.as_view(), name="register-organization"),
    path("wyloguj/", views.Logout.as_view(), name="logout"),
]

dobrodzieje/templates/partials/navbar.html
{% load notifications_tags %}

<nav class="navbar navbar-expand navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'webapp:index'%}">Dobrodzieje</a>
      <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> -->
  
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'index' %}active{% endif %}" href="{% url 'webapp:index'%}">O stronie</a>
          </li>          
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'announcement-list' %}active{% endif %}" href="{% url 'webapp:announcement-list'%}">Przeglądaj ogłoszenia</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'for-organizations' %}active{% endif %}" href="{% url 'webapp:for-organizations'%}">Dla organizacji</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if navbar_active == 'for-creators' %}active{% endif %}" href="{% url 'webapp:for-creators'%}">Dla twórców</a>
          </li>

        </ul>
        <ul class="navbar-nav me-end">
          {% if user.is_organization %}
            <li class="nav-item">
              <a class="nav-link {% if navbar_active == 'my-announcement' %}active{% endif %}" href="{% url 'webapp:my-announcement'%}">Moje ogłoszenia</a>
            </li>
          {% endif %}          
          {% if user.is_creator %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:my-teams'%}">Moje Drużyny</a>
            </li>
          {% endif %}
          {% if user.is_authenticated %}          
            <li class="nav-item">
              <a class="nav-link" href="#">
                {% show_notifications %}
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
              <div class="dropdown-menu dropdown-menu-end">
                <a class="dropdown-item" href="{% url 'webapp:edit-profile'%}">Ustawienia Konta</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'webapp:logout' %}">Wyloguj się</a>
              </div>
            </li>
          {% endif %}
          {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if navbar_active == 'login' %}active{% endif %}" href="{% url 'webapp:login' %}">Zaloguj się</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if navbar_active == 'register' %}active{% endif %}" href="{% url 'webapp:register' %}">Zarejestruj się</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

dobrodzieje/templates/partials/pagination.html
{% comment %} {% if is_paginated %} {% endcomment %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% comment %} {% endif %} {% endcomment %}