chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path('<int:team_id>', views.TeamChat.as_view(), name='team-chat'),
    path('<int:team_id>/wiadomosci', views.LoadMessages.as_view(), name='load-messages'),
    path('<int:team_id>/ustawienia', views.UpdateTeamSettings.as_view(), name='update-team-settings'),
    path('<int:team_id>/druzyna', views.DeleteTeam.as_view(), name='delete-team'),
    path('<int:team_id>/czlonkowie', views.RemoveUserFromTeam.as_view(), name='delete-team-member'),
    path('<int:team_id>/dolacz/<int:team_member_id>', views.JoinChat.as_view(), name='join-chat'),
]

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("dla-tworcow/", views.ForCreators.as_view(), name="for-creators"),
    path("dla-organizacji/", views.ForOrganizations.as_view(), name="for-organizations"),
    path("przegladaj-ogloszenia/", views.AnnouncementList.as_view(), name="announcement-list"),
    path("moje-ogloszenie/", views.MyAnnouncement.as_view(), name="my-announcement"),
    path("ogloszenie/<int:id>/", views.AnnouncementDetails.as_view(), name="announcement-detail"),
    path("stworz-ogloszenie/", views.AnnouncementCreate.as_view(), name="announcement-create"),
    path("edytuj-ogłoszenie/", views.AnnouncementUpdate.as_view(), name="announcement-edit"),
    path("usun-ogłoszenie/", views.AnnouncementDelete.as_view(), name="announcement-delete"),
    path("moje-druzyny/", views.MyTeams.as_view(), name="my-teams"),
    path("edytuj-profil/", views.EditProfile.as_view(), name="edit-profile"),
    path("zaloguj/", views.Login.as_view(), name="login"),
    path("zarejestruj/", views.Register.as_view(), name="register"),
    path("zarejestruj/tworca/", views.RegisterCreator.as_view(), name="register-creator"),
    path("zarejestruj/organizacja/", views.RegisterOrganization.as_view(), name="register-organization"),
    path("wyloguj/", views.Logout.as_view(), name="logout"),
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.postgres.fields import ArrayField
from ckeditor.fields import RichTextField
from django.contrib import admin
from django.urls import reverse
from .managers import (
    CustomAccountManager, 
    AnnouncementQuerySetManager, 
    CityManager
)

import bleach


# Set ckeditor sanitizing rules
bleach.sanitizer.ALLOWED_TAGS += ['p', 'span', 'u', 'ul', 'ol', 'hr', 'img' ,'div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6','pre', 'address', 'strong', 'br']
bleach.sanitizer.ALLOWED_ATTRIBUTES.update({'*': ['style'], 'img': ['alt', 'src']})
bleach.sanitizer.ALLOWED_STYLES += ['color', 'font-size', 'text-align', 'list-style-type', 'background-color', 'height', 'width', 'margin-left', 'float', 'margin', 'border-width', 'border-style']

# ===== Choices =====
# info https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types
class Roles(models.TextChoices):
    FRONTEND = ('FE', 'Front-End Developer')
    FULLSTACK = ('FS', 'Full-Stack Developer')
    BACKEND = ('BE', 'Back-End Developer')
    DESIGNER = ('GD', 'Graphic Designer')

    @classmethod
    def get_labels_by_values(cls, values):
        return [role_name for (role_value, role_name) in Roles.choices if role_value in values]


# ===== Models =====
class User(AbstractBaseUser,PermissionsMixin):
    objects = CustomAccountManager()

    email = models.EmailField(unique=True, blank=False)
    is_organization = models.BooleanField('is organization?', default=False)
    is_creator = models.BooleanField('is creator?', default=False)
    is_staff = models.BooleanField('staff status', default=False)
    is_active = models.BooleanField('active', default=True)
    date_joined = models.DateTimeField('date joined', auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class Voivodeship(models.Model):
    name = models.CharField(max_length=255,  unique=True)

    def __str__(self):
        return self.name


class City(models.Model):
    objects = CityManager()

    voivodeship = models.ForeignKey(Voivodeship, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Cities'
        ordering = ('name',)
        unique_together = ['voivodeship', 'name']

    def __str__(self):
        return self.name


class Organization(models.Model):
    ORGANIZATION_CATEGORY_CHOICES = [
        ('DP', 'Działalnośc prospołeczna'),
        ('EiW', 'Edukacja i wychowanie'),
        ('WON', 'Wspanie osób niepełnosprawnych'),
        ('KSiT', 'Kultura, Sztuka i Technologia'),
        ('OZiZ', 'Ochrona zdrowia i życia'),
        ('DCh', 'Działalność charytatywna'),
        ('PDzi', 'Pomoc Dzieciom'),
        ('SiR', 'Sport i rekreacja'),
        ('OSiPZ', 'Ochorna środowiska i praw zwierząt')
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField('organization\'s name', max_length=255, unique=True)
    category = models.CharField(max_length=10, choices=ORGANIZATION_CATEGORY_CHOICES)
    phone_number = models.CharField('phone number', max_length=9, blank=True, null=True)
    fb_url = models.URLField('facebook page URL', blank=True, null=True)
    twitter_url = models.URLField('twitter accout URL', blank=True, null=True)
    KRS = models.CharField(max_length=10, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Creator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField('first name', max_length=150, blank=True, null=True)
    last_name = models.CharField('last name', max_length=150, blank=True, null=True)


    def __str__(self):
        return f'{self.user}' + \
               (f' ({self.last_name}, {self.first_name})' if (self.first_name and self.last_name) else '')


class Announcement(models.Model):
    objects = AnnouncementQuerySetManager.as_manager()

    organization = models.OneToOneField(Organization, on_delete=models.CASCADE)
    logo = models.ImageField('organization\'s logo', upload_to='logos/', blank=True, null=True)
    content = RichTextField('what needs to be done', blank=False, null=False)
    #TODO images of the future website??
    old_website = models.URLField('previous organization\'s website', blank=True, null=True)
    created_on = models.DateTimeField('created on', auto_now_add=True)

    def __str__(self):
        return f'Announcement by {self.organization}'

    def get_absolute_url(self):
        return reverse('webapp:announcement-detail', kwargs={'id': self.id})

    def is_author(self, user):
        return self.organization.user == user

    def save(self, *args, **kwargs):
        self.content = bleach.clean(self.content)
        super().save(*args, **kwargs)


class Team(models.Model):

    TECHNOLOGIES_CHOICES = [
        ('PY', 'python'),
        ('NJS', 'node.js'),
        ('PHP', 'php'),
        ('ROR', 'ruby on rails'),
        ('JSP', 'java'),
        ('ASX', '.net'),
        ('GO', 'golang'),
        ('HC', 'html&css'),
        ('JS', 'javascript'),
        ('TS', 'typescript'),
        ('JSX', 'react'),
        ('ANG', 'angular'),
        ('VUE', 'vue.js'),
        ('CPP', 'c++'),
        ('C', 'c'),
        ('RN', 'react native'),
        ('FL', 'flutter'),
        ('SC', 'scala'),
        ('EX', 'elixir'),
        ('KT', 'kotlin')
    ]


    announcement = models.OneToOneField(Announcement, on_delete=models.CASCADE)
    is_closed = models.BooleanField('is closed?', default=False)
    members = models.ManyToManyField(Creator, related_name='teams', through='TeamMember')
    # info https://docs.djangoproject.com/en/dev/ref/contrib/postgres/fields/#arrayfield
    our_stack = ArrayField(
        models.CharField('What technologies we use?', max_length=3, choices=TECHNOLOGIES_CHOICES),
        blank=True, 
        null=True
    )
    looking_for = ArrayField(
        models.CharField('looking for those roles', max_length=2, choices=Roles.choices),
        blank=True, 
        null=True
    )

    def __str__(self):
        return f'Team for {self.announcement}'

    def get_absolute_url(self):
        return reverse("chat:team-chat", kwargs={"team_id": self.id})

    def get_admin(self):
        return self.teammember_set.get(is_admin=True).creator.user


# Jak używać many to many https://youtu.be/-HuTlmEVOgU?t=890
class TeamMember(models.Model):
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    role = models.CharField(max_length=2, choices=Roles.choices, null=True)
    is_admin = models.BooleanField('is admin?', default=False)
    nick = models.CharField(max_length=50, null=True)
    joined = models.BooleanField('user joined?', default=False)

    @admin.display(description='Creator')
    def show_creator(self):
        return str(self.creator)    

    @admin.display(description='Team')
    def show_team(self):
        return str(self.team)

    class Meta:
        unique_together = ['creator', 'team']

webapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from ckeditor.widgets import CKEditorWidget
from django.forms import widgets
from .models import Announcement, Team, User, Organization, Creator, City, Roles
from django.db import transaction

class OrganizationFieldsMixin(forms.ModelForm):
    name = forms.CharField(required=True, label='Nazwa organizacji',
                           widget=forms.TextInput(attrs={'aria-label': 'Podaj nazwę organizacji'}))
    category = forms.ChoiceField(choices=Organization.ORGANIZATION_CATEGORY_CHOICES, label='Kategoria', 
                                 widget=forms.Select(attrs={'aria-label': 'Wybierz kategorię'}))
    phone_number = forms.CharField(required=False, label='Numer telefonu', max_length=9,
                                   widget=forms.TextInput(attrs={'aria-label': 'Wpisz numer telefonu'}))
    fb_url = forms.URLField(required=False, label='Strona na Facebook', 
                            widget=forms.URLInput(attrs={
                                'placeholder': 'Wpisz adres strony (np. https://www.facebook.com/PolskaAkcjaHumanitarna/)',
                                'aria-label': 'Wpisz adres strony (np. https://www.facebook.com/PolskaAkcjaHumanitarna/)'
                            }))
    twitter_url = forms.URLField(required=False, label='Konto na Twitter', 
                                 widget=forms.URLInput(attrs={
                                     'placeholder': 'Wpisz adres strony (np. https://twitter.com/PAH_org)',
                                     'aria-label': 'Wpisz adres strony (np. https://twitter.com/PAH_org)'
                                 }))
    KRS = forms.CharField(required=False, label='Numer KRS', max_length=10,
                          widget=forms.TextInput(attrs={'aria-label': 'Podaj numer KRS'}))                   
    city = forms.ModelChoiceField(required=False, label='Miasto', queryset=City.objects.all())


class OrganizationRegisterForm(UserCreationForm, OrganizationFieldsMixin):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get('email')
        user.is_organization = True
        user.save()
        organization = Organization(user=user)
        organization.name = self.cleaned_data.get('name')
        organization.category = self.cleaned_data.get('category')
        organization.phone_number = self.cleaned_data.get('phone_number')
        organization.fb_url = self.cleaned_data.get('fb_url')
        organization.twitter_url = self.cleaned_data.get('twitter_url')
        organization.KRS = self.cleaned_data.get('KRS')
        organization.city = self.cleaned_data.get('city')
        organization.save()
        return user
        
    def clean(self):
        cleaned_data = super().clean()

        fb_url = cleaned_data.get('fb_url')
        twitter_url = cleaned_data.get('twitter_url')

        if fb_url:
            if 'facebook.com' not in fb_url:
                self.add_error('fb_url', 'Podany adres nie należy do Facebook\'a') 
        
        if twitter_url:
            if 'twitter.com' not in twitter_url:
                self.add_error('twitter_url', 'Podany adres nie należy do Twitter\'a') 

        return cleaned_data


class CreatorRegisterForm(UserCreationForm):
    first_name = forms.CharField(required=False, label='Imię',
                                 widget=forms.TextInput(attrs={'aria-label': 'Podaj imię'}))
    last_name = forms.CharField(required=False, label='Nazwisko',
                                widget=forms.TextInput(attrs={'aria-label': 'Podaj nazwisko'}))

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get('email')
        user.is_creator = True
        user.save()
        creator = Creator(user=user)
        creator.first_name = self.cleaned_data.get('first_name')
        creator.last_name = self.cleaned_data.get('last_name')
        creator.save()
        return user


class AnnouncementForm(forms.ModelForm):
    logo = forms.ImageField(required=False, label='Logo organizacji',
                            widget=forms.FileInput(attrs={'aria-label': 'Prześlij logo organizacji'}))
    old_website = forms.URLField(required=False, label='Adres obecnej strony (jeśli istnieje)',
                                 widget=forms.URLInput(attrs={'aria-label': 'Adres obecnej strony (jeśli istnieje)'}))
    content  = forms.CharField(required=True, label='Treść ogłoszenia', 
                               widget=CKEditorWidget(attrs={'aria-label': 'Podaj treść ogłoszenia'}))
    #TODO def clean_content(self): - NO SCRIPTS

    class Meta:
        model = Announcement
        fields = ['content', 'logo', 'old_website']


class OrganizationEditForm(OrganizationFieldsMixin):
    class Meta:
        model = Organization
        fields = ['name', 'category', 'phone_number', 'fb_url', 'twitter_url', 'KRS', 'city']


class CreatorEditForm(forms.ModelForm):
    class Meta:
        model = Creator
        fields = ['first_name', 'last_name']


class TeamJoinForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['looking_for']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        team = kwargs['instance']
        # Show only roles that are looked for by the team
        limited_choices = [(role_value, role_name) for (role_value, role_name) in Roles.choices if role_value in team.looking_for]
        self.fields['looking_for'] = forms.ChoiceField(label='Wybierz rolę', choices=limited_choices)

webapp/templates/webapp/announcemenet_delete.html
{% extends 'layout.html' %}

{% block content %}
{% comment %} #TODO move to modal {% endcomment %}
    <form method="POST">
        {% csrf_token %}
        <h1>Czy chcesz usunąć to ogłoszenie?</h1>
        <div>
            <input type="submit" value="Yes">
            <a href="../">Anuluj</a>
        </div>
    </form>
{% endblock %}

webapp/templates/webapp/announcement_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        {% if is_author %}
            {% include 'webapp/partials/announcement_delete_modal.html' %}
            <div>
                <a class="btn btn-secondary" href="{% url "webapp:announcement-edit" %}">Edytuj ogłoszenie</a>
                <!-- Button trigger delete announcement modal -->
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteAnnouncementModal">
                    Usuń ogłoszenie
                </button>
            </div>
        {% endif %}
        {% include 'webapp/partials/show_announcement_badge.html' with announcement_state=announcement_state team=team %}
        {% if is_creator %}
            {% if announcement_state == 'no team' %}
                {% include 'webapp/partials/form_no_team.html' with organization_id=announcement.organization.user.id %}
            {% elif announcement_state == 'team opened' %}
                {% include 'webapp/partials/form_team_opened.html' with team=team organization_id=announcement.organization.user.id looking_for_form=looking_for_form%}
            {% endif %}
        {% endif %}       

        {{announcement.organization}}
        {{announcement.content|safe}}
    </div>
{% endblock %}

webapp/templates/webapp/announcement_edit.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% comment %} #TODO force to show messages for required fields {% endcomment %}
{% block content %}
    <div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Nazwa Organizacji</label>
            <input type="text" id="name" class="form-control"  value="{{ organization.name }}" disabled>
        </div>
        <div class="form-group">
            <label for="category">Kategoria</label>
            <input type="text" id="category" class="form-control"  value="{{ organization.get_category_display }}" disabled>
        </div>
        <div class="form-group">
            <label for="phone_number">Numer Telefonu</label>
            <input type="text" id="phone_number" class="form-control"  value="{{ organization.phone_number|default_if_none:"" }}" disabled>
        </div>
        <div class="form-group">
            <label for="fb_url">Adres strony Facebook</label>
            <input type="text" id="fb_url" class="form-control"  value="{{ organization.fb_url|default_if_none:"" }}" disabled>
        </div>
        <div class="form-group">
            <label for="twitter_url">Adres konta Twitter</label>
            <input type="text" id="twitter_url" class="form-control"  value="{{ organization.twitter_url|default_if_none:"" }}" disabled>
        </div>
        <div class="form-group">
            <label for="krs">Number KRS</label>
            <input type="text" id="krs" class="form-control"  value="{{ organization.KRS|default_if_none:"" }}" disabled>
        </div>        
        <div class="form-group">
            <label for="krs">Miasto</label>
            <input type="text" id="city" class="form-control"  value="{{ organization.city|default_if_none:"" }}" disabled>
        </div>
        {{ form.media }}
        {{ form|crispy }}
        <input type="submit" value="Zapisz">
    </form>
    </div>

    <script>

    </script>
{% endblock %}

webapp/templates/webapp/announcement_empty.html
{% extends 'layout.html' %}

{% block content %}
    There is nothing here please add an announcement
    <input type="button" class="btn btn-primary" onclick="location.href='{% url "webapp:announcement-create" %}'" value="Stwórz Ogłoszenie">
{% endblock %}

webapp/templates/webapp/edit_profile.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class='btn btn-primary' value="Zapisz">
    </form>
    </div>
{% endblock %}

webapp/templates/webapp/for_creators.html
{% extends 'layout.html' %}

{% block content %}
<ol>
    <li>Jak się zarejestrować i używać (konto)</li>
    <li>
        Jak szukać organizacji
        <ul>
            <li>Wybierz kategorię</li>
            <li>Wybierz lokalizację</li>
            <li>Wybierz organizację</li>
        </ul>
    </li>
    <li>Jak pomóc wybranej organizacji</li>
    <ul>
        <li>Skontaktuj się z organizacją</li>
        <li>Zaproś ludzi do drużyny</li>
        <li>Stwórzcie kosztorys (uruchomienie i utrzymanie strony)</li>
    </ul>
</ol>

{% endblock %}

webapp/templates/webapp/for_organizations.html
{% extends 'layout.html' %}

{% block content %}
<ol>
    <li>Jak się zarejestrować i używać</li>
    <li>
        Podstawowe zasady bezpieczeństwa
        <ul>
            <li>Strona nie powinna mieć logowania</li>
            <li>Spytaj ile będzie kosztowała strona i jej utrzymanie</li>
            <li>Spytaj co należy zrobić w przypadku problemów</li>
        </ul>
    </li>
    <li>Jak pomóc twórcom</li>
    <ul>
        <li>Opisz jak ma wyglądać strona</li>
        <li>Opisz co ma zawierać</li>
    </ul>
    <li>Wyślij rysunki poglądowe</li>
</ol>

{% endblock %}

webapp/templates/webapp/index.html
{% extends 'layout.html' %}


{% block content %}
Home page
{{user}}
{% endblock %}

webapp/templates/webapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'webapp/css/bootstrap.min.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Dobrodzieje</title>
</head>
<body>
    {% include "webapp/partials/navbar.html" %}
    {% block content %}

    {% endblock %} 
</body>
</html>

webapp/templates/webapp/login.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form action="{% url 'webapp:login' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Zaloguj się</button>
    </form>
</div>

{% endblock %}

webapp/templates/webapp/register.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
Register
<a href="{% url 'webapp:register-creator' %}">Tworca</a>
<a href="{% url 'webapp:register-organization' %}">Organizacja</a>


{% endblock %}

webapp/templates/webapp/register_creator.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Zarejestruj się</button>
    </form>
</div>

{% endblock %}

webapp/templates/webapp/register_organization.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Zarejestruj się</button>
    </form>
</div>

{% endblock %}

webapp/templates/webapp/teams_list.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-3">
        {% for team in teams %}
            {% include "webapp/partials/team_preview.html" with team=team %}
        {% endfor %}
    </div>

    {% include "partials/pagination.html" %}
{% endblock %}