chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path('<int:team_id>', views.TeamChat.as_view(), name='team-chat'),
    path('<int:team_id>/wiadomosci', views.LoadMessages.as_view(), name='load-messages'),
    path('<int:team_id>/ustawienia', views.UpdateTeamSettings.as_view(), name='update-team-settings'),
    path('<int:team_id>/druzyna', views.DeleteTeam.as_view(), name='delete-team'),
    path('<int:team_id>/czlonkowie', views.RemoveUserFromTeam.as_view(), name='delete-team-member'),
    path('<int:team_id>/dolacz/<int:team_member_id>', views.JoinChat.as_view(), name='join-chat'),
]

notifications/urls.py
from django.urls import path
from . import views

app_name='notifications'
urlpatterns = [
    #Join announcement
    path('join-announcement', views.JoinAnnouncement.as_view(), name='join-announcement'),
    path('cancel-join-announcement', views.CancelJoinAnnouncement.as_view(), name='cancel-join-announcement'),
    path('join-announcement-acceptance', views.JoinAnnouncementAcceptance.as_view(), name='join-announcement-acceptance'),
    path('join-announcement-rejection', views.JoinAnnouncementRejection.as_view(), name='join-announcement-rejection'),
    # Join Team
    path('join-team', views.JoinTeam.as_view(), name='join-team'),
    path('cancel-join-team', views.CancelJoinTeam.as_view(), name='cancel-join-team'),
    path('join-team-acceptance', views.JoinTeamAcceptance.as_view(), name='join-team-acceptance'),
    path('join-team-rejection', views.JoinTeamRejection.as_view(), name='join-team-rejection'),
]

notifications/models.py
from django.db import models
from django.db.models.fields.json import JSONField
from webapp.models import User


class Notification(models.Model):
    class NotificationType(models.IntegerChoices):
        NEW_MESSAGE = 1, 'New Message'
        JOIN_ANNOUNCEMENT_REQUEST = 2, 'Join Announcement Request'
        JOIN_TEAM_REQUEST = 3, 'Join Team Request'
        JOIN_RESPONSE = 4, 'Join Response'
        DELETION = 5, 'Deletion'


    notification_type = models.IntegerField(choices=NotificationType.choices)
    sender = models.ForeignKey(User, related_name='notification_from', on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='notification_to', on_delete=models.CASCADE)
    message = models.CharField(max_length=255)
    related_url = models.URLField('related url', max_length=255, null=True, blank=True)
    created_on = models.DateTimeField('created on', auto_now_add=True)
    read = models.BooleanField(default=False)
    extra_data = JSONField(blank=True, null=True)

notifications/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.html import format_html
from django.views.generic import View

from webapp.models import (
    Announcement,
    Organization,
    User,
    Team,
    Creator,
    TeamMember,
    Roles
)

from .models import Notification
from .views_mixins import (
    JoinAnnouncementMixin, 
    JoinAnnouncementResponseMixin,
    JoinTeamResponseMixin
)


class JoinAnnouncement(JoinAnnouncementMixin, View):
    def post(self, request, *args, **kwargs):
        notification_data = super().get_notification_data(request)

        # Handle errors
        if notification_data.get('error_with_redirect'):
            return notification_data['error_with_redirect']
        
        sender = notification_data['sender']
        recipient = notification_data['recipient']
        notification_type = notification_data['notification_type']
        message = f'Użytkownik {sender} chce pracować nad Twoją nową stroną'

        Notification.objects.create(
            sender = sender,
            recipient = recipient,
            message = message,
            notification_type = notification_type
        )
        return redirect(request.META.get('HTTP_REFERER'))


class CancelJoinAnnouncement(JoinAnnouncementMixin, View):
    def post(self, request, *args, **kwargs):
        notification_data = super().get_notification_data(request)

        # Handle errors
        if notification_data.get('error_with_redirect'):
            return notification_data['error_with_redirect']

        sender = notification_data['sender']
        recipient = notification_data['recipient']
        notification_type = notification_data['notification_type']
        try:
            Notification.objects.get(sender=sender, recipient=recipient, notification_type=notification_type).delete()
        except Notification.DoesNotExist:
            messages.error(
                    request, 
                    message='Prośba o stworzenie drużyny nie istnieje  🤷‍♂️',
                    extra_tags='alert-danger'
                )
            return {'error_with_redirect': redirect(reverse_lazy('webapp:index'))}
        return redirect(request.META.get('HTTP_REFERER'))


class JoinAnnouncementAcceptance(JoinAnnouncementResponseMixin, View):
    def post(self, request, *args, **kwargs):
        notification_data = super().get_notification_data(request)

        # Handle errors
        if notification_data.get('error_with_redirect'):
            return notification_data['error_with_redirect']
        
        # Get data from the form
        organization_user = notification_data['organization_user']
        creator_user = notification_data['creator_user']
        notification_type = notification_data['notification_type']

        # Create a new Team
        organization_announcement = Announcement.objects.get(organization__user=organization_user)
        new_team = Team.objects.create(
            announcement = organization_announcement,
            is_closed = True
        )
                                                           
        # Add the user as a TeamMember admin 
        TeamMember.objects.create(
            creator = creator_user.creator,
            team = new_team,
            is_admin = True
        )

        # Notify all rejected users
        all_join_requests = Notification.objects.filter(recipient=organization_user, 
                                                        notification_type=Notification.NotificationType.JOIN_ANNOUNCEMENT_REQUEST)
        join_requests_rejected = all_join_requests.exclude(sender=creator_user)
        for join_request in join_requests_rejected:
            Notification.objects.create(
                sender = organization_user, 
                recipient = join_request.sender, 
                notification_type = notification_type,
                message = 'Argh! Inne zgłoszenie zostało już przyjęte do tego ogłoszenia. Spróbuje gdzie indziej i nie trać zapału!'
            )

        # Delete all join request notifications
        all_join_requests.delete()
        
        # Create notification that the user's request got accepted
        Notification.objects.create(
            sender = organization_user, 
            recipient = creator_user, 
            notification_type = notification_type,
            message = f'Gratulacje twoja prośba o dołączenie do {organization_user.organization} została zaakcaptowana!',
            related_url = new_team.get_absolute_url()
        )

        # Add message that the user is working on your website
        messages.info(
            request, 
            message='Gratulacje! Twoja strona już się tworzy!',
            extra_tags='alert-success'
        )
        
        # Redirect to the announcement
        return redirect(organization_announcement.get_absolute_url())


class JoinAnnouncementRejection(JoinAnnouncementResponseMixin, View):
    def post(self, request, *args, **kwargs):
        notification_data = super().get_notification_data(request)

        # Handle errors
        if notification_data.get('error_with_redirect'):
            return notification_data['error_with_redirect']

        organization_user = notification_data['organization_user']
        creator_user = notification_data['creator_user']
        notification_type = notification_data['notification_type']
        join_request_notif = notification_data['join_request_notif']
        message = f'😢 Twoja prośba o dołączenie do {organization_user.organization} została odrzucona. Skontaktuj się z organizacją jeśli chcesz wyjaśnić sytuację'

        # Create notification that the user's request got rejected
        Notification.objects.create(
            sender = organization_user, 
            recipient = creator_user, 
            notification_type = notification_type,
            message = message,
        )

        # Delete this join request notification
        join_request_notif.delete()

        return redirect(request.META.get('HTTP_REFERER'))

class JoinTeam(View):
    def post(self, request, *args, **kwargs):
        form_data = request.POST
        role_value = form_data['looking_for']
        
        try:
            # Confirm that the team is opened and is looking for this role
            team = Team.objects.get(
                        id = form_data['team_id'],
                        is_closed = False,
                        looking_for__contains = [role_value]
                   )
            
            # Get data for the notification's message
            organization = Organization.objects.get(user__id=form_data['organization'])
            role_name = Roles.get_labels_by_values(role_value)[0]
        except Team.DoesNotExist:
            messages.error(
                request, 
                message='Drużyna nie istnieje 🤷‍♂️',
                extra_tags='alert-danger'
            )
            return redirect(reverse_lazy('webapp:index'))
        except Organization.DoesNotExist:
            messages.error(
                request, 
                message='Organizacja nie istnieje 🤷‍♂️',
                extra_tags='alert-danger'
            )
            return redirect(reverse_lazy('webapp:index'))  
        
        
        # Gather all the data and send notification to the team's admin
        sender = request.user
        recipient = team.get_admin()
        notification_type = Notification.NotificationType.JOIN_TEAM_REQUEST
        message = f'chce dołączyć do drużyny dla {organization} na stanowisko {role_name}'
        extra_data = {'team_id': team.id, 
                      'role': {'value': role_value, 'name': role_name},
                      'organization': organization.name
                    }
        Notification.objects.create(
            sender = sender,
            recipient = recipient,
            message = message,
            notification_type = notification_type,
            extra_data = extra_data
        )
        return redirect(request.META.get('HTTP_REFERER'))


class CancelJoinTeam(View):
    def post(self, request, *args, **kwargs):       
        try:
            team = Team.objects.get(id=request.POST['team_id'], is_closed=False)
        except Team.DoesNotExist:
            messages.error(
                request, 
                message='Drużyna nie istnieje 🤷‍♂️',
                extra_tags='alert-danger'
            )
            return redirect(reverse_lazy('webapp:index'))

        sender = request.user
        recipient = team.get_admin()
        notification_type = Notification.NotificationType.JOIN_TEAM_REQUEST

        try:
            Notification.objects.get(
                sender=sender, 
                recipient=recipient, 
                notification_type=notification_type, 
                extra_data__team_id = team.id
            ).delete()
        except Notification.DoesNotExist:
            messages.error(
                    request, 
                    message='Prośba o dołączenie drużyny nie istnieje  🤷‍♂️',
                    extra_tags='alert-danger'
                )
            return redirect(reverse_lazy('webapp:index'))

        return redirect(request.META.get('HTTP_REFERER'))


class JoinTeamAcceptance(JoinTeamResponseMixin, View):
    def post(self, request, *args, **kwargs):
        notification_data = super().get_notification_data(request)

        # Handle errors
        if notification_data.get('error_with_redirect'):
            return notification_data['error_with_redirect']

        team_admin = notification_data['team_admin']
        applicant = notification_data['applicant']
        notification_type = notification_data['notification_type']
        join_request_notif = notification_data['join_request_notif']
        
        try:
            team = Team.objects.get(id=request.POST.get('team-id'))
        except Team.DoesNotExist:

notifications/templates/notifications/partials/join_announcement_notification.html
{{ notification.sender }} - 
{{ notification.recipient }} - 
{{ notification.message }} - 
{{ notification.notification_type }}

<!-- Button trigger modal -->
<button type="button" 
        class="btn btn-primary js-accept-request" 
        data-bs-toggle="modal" 
        data-bs-target="#requestModal" 
        data-sender-id="{{ notification.sender.id }}"
        data-sender-email="{{ notification.sender }}"
        data-join-request-type="{{ notification.get_notification_type_display }}"
        data-form-url="
          {% if notification.get_notification_type_display == 'Join Announcement Request' %}
            {% url 'notifications:join-announcement-acceptance' %}
          {% else %}
            {% url 'notifications:join-team-acceptance' %}
          {% endif %}">
  Akceptuj
</button>
<button type="button" 
        class="btn btn-danger js-reject-request" 
        data-bs-toggle="modal" 
        data-bs-target="#requestModal"
        data-sender-id="{{ notification.sender.id }}"
        data-sender-email="{{ notification.sender }}"
        data-join-request-type="{{ notification.get_notification_type_display }}"
        data-form-url="
          {% if notification.get_notification_type_display == 'Join Announcement Request' %}
            {% url 'notifications:join-announcement-rejection' %}
          {% else %}
            {% url 'notifications:join-team-rejection' %}
          {% endif %}">

  Odrzuć
</button>

notifications/templates/notifications/partials/join_notification.html
{{ notification.sender }} - 
{{ notification.recipient }} - 
{{ notification.message }} - 
{{ notification.notification_type }}

<!-- Button trigger modal -->
<button type="button" 
        class="btn btn-primary js-accept-request" 
        data-bs-toggle="modal" 
        data-bs-target="#requestModal" 
        data-sender-id="{{ notification.sender.id }}"
        data-sender-email="{{ notification.sender }}"
        data-join-request-type="{{ notification.get_notification_type_display }}"
        {% if notification.get_notification_type_display == 'Join Announcement Request' %}
          data-form-url="{% url 'notifications:join-announcement-acceptance' %}"
        {% else %}
          data-form-url="{% url 'notifications:join-team-acceptance' %}"
          data-team-id="{{notification.extra_data.team_id}}"
        {% endif %}>
  Akceptuj 
</button>
<button type="button" 
        class="btn btn-danger js-reject-request" 
        data-bs-toggle="modal" 
        data-bs-target="#requestModal"
        data-sender-id="{{ notification.sender.id }}"
        data-sender-email="{{ notification.sender }}"
        data-join-request-type="{{ notification.get_notification_type_display }}"
        {% if notification.get_notification_type_display == 'Join Announcement Request' %}
          data-form-url="{% url 'notifications:join-announcement-rejection' %}"
        {% else %}
          data-form-url="{% url 'notifications:join-team-rejection' %}"
          data-team-id="{{notification.extra_data.team_id}}"
        {% endif %}>

  Odrzuć
</button>

notifications/templates/notifications/partials/join_request_modal.html
<div class="modal fade" id="requestModal" tabindex="-1" aria-labelledby="requestModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title js-modal-title" id="requestModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-dark js-modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Anuluj</button>
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="creator" class="js-creator-input">
            <input type="hidden" name="team-id" class="js-team-id-input">
            <button type="submit" class="btn btn-primary">Potwiedź</button>
        </form>
      </div>
    </div>
  </div>
</div>

notifications/templates/notifications/partials/join_request_notif.html
{{ notification.sender }} - 
{{ notification.recipient }} - 
{{ notification.message }} - 
{{ notification.notification_type }}

<!-- Button trigger modal -->
<button type="button" 
        class="btn btn-primary js-accept-request" 
        data-bs-toggle="modal" 
        data-bs-target="#requestModal" 
        data-sender-id="{{ notification.sender.id }}"
        data-sender-email="{{ notification.sender }}"
        data-join-request-type="{{ notification.get_notification_type_display }}"
        {% if notification.get_notification_type_display == 'Join Announcement Request' %}
          data-form-url="{% url 'notifications:join-announcement-acceptance' %}"
        {% else %}
          data-form-url="{% url 'notifications:join-team-acceptance' %}"
          data-team-id="{{notification.extra_data.team_id}}"
        {% endif %}>
  Akceptuj 
</button>
<button type="button" 
        class="btn btn-danger js-reject-request" 
        data-bs-toggle="modal" 
        data-bs-target="#requestModal"
        data-sender-id="{{ notification.sender.id }}"
        data-sender-email="{{ notification.sender }}"
        data-join-request-type="{{ notification.get_notification_type_display }}"
        {% if notification.get_notification_type_display == 'Join Announcement Request' %}
          data-form-url="{% url 'notifications:join-announcement-rejection' %}"
        {% else %}
          data-form-url="{% url 'notifications:join-team-rejection' %}"
          data-team-id="{{notification.extra_data.team_id}}"
        {% endif %}>

  Odrzuć
</button>

notifications/templates/notifications/partials/join_response_notif.html
{{ notification.sender }} - 
{{ notification.recipient }} - 
{{ notification.message }} - 
{{ notification.notification_type }}
{% comment %} #TODO only if accepted {% endcomment %}
<a href="{{ notification.related_url }}">przejdź do czatu</a>